# Generated by Django 4.2.7 on 2024-04-21 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strains',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('UIN', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('pedigree', models.TextField()),
                ('mutations', models.TextField()),
                ('transformations', models.TextField()),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('access', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SubstanceIdentification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification_date', models.DateField()),
                ('results', models.TextField()),
                ('identified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.users')),
                ('strain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.strains')),
            ],
        ),
        migrations.AddField(
            model_name='strains',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.users'),
        ),
        migrations.CreateModel(
            name='StrainProcessing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('processing_date', models.DateField()),
                ('description', models.TextField()),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.users')),
                ('strain_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.strains')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('results', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.users')),
            ],
        ),
        migrations.CreateModel(
            name='Experiments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('growth_medium', models.TextField()),
                ('results', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.users')),
                ('strain_UIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.strains')),
            ],
        ),
        migrations.CreateModel(
            name='Cultures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planning_date', models.DateField()),
                ('results', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.users')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.projects')),
            ],
        ),
        migrations.CreateModel(
            name='CultivationPlanning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strain_ID', models.UUIDField()),
                ('planning_date', models.DateField()),
                ('completion_date', models.DateField()),
                ('growth_medium', models.TextField()),
                ('status', models.TextField()),
                ('started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biobaseapp.users')),
            ],
        ),
    ]
